"""Test the P195-strengthened CORE_VERIFICATION_PROMPT against the
live text LLM using each of the 6 worked-example scenarios.

For every scenario we send the real condition + document text and
check that the LLM returns the expected verdict (PASS or FAIL).
"""
import json
import sys
import time
from pathlib import Path

ROOT = Path(r"d:/COMPLYTRADE/V7/FINAL/Trade-Finance-Final")
sys.path.insert(0, str(ROOT))

from config.settings import QWEN_TEXT_LLM_URL, QWEN_TEXT_LLM_MODEL  # noqa
from steps.step14_verification import CORE_VERIFICATION_PROMPT  # noqa
import requests  # noqa


CASES = [
    {
        "name": "Consignee TO ORDER without endorsement (expect FAIL)",
        "condition_text": "Bill of lading must be made out to the order of Bank Al Habib Ltd., Pakistan.",
        "clause_ref": "46A-2",
        "lc_field_value": "BANK AL HABIB LTD., PAKISTAN",
        "lc_parties": "Issuing Bank: BANK AL HABIB LTD.\nBeneficiary: OLAM GLOBAL AGRI PTE LTD",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"consignee": "TO ORDER", "notify_party": "TRANSSSION TECNO ELECTRONICS (PVT) LTD. AND BANK AL HABIB LTD., PAKISTAN"}',
        "document_text": "CONSIGNEE: TO ORDER\nNOTIFY PARTY: TRANSSSION TECNO ELECTRONICS (PVT) LTD. AND BANK AL HABIB LTD., PAKISTAN\nSHIPPER: OLAM GLOBAL AGRI PTE LTD",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "BL shipper is different entity from beneficiary (expect FAIL)",
        "condition_text": "Bill of Lading must show the Beneficiary as the Shipper.",
        "clause_ref": "47A-3",
        "lc_field_value": "OLAM GLOBAL AGRI PTE LTD",
        "lc_parties": "Beneficiary: OLAM GLOBAL AGRI PTE LTD, 7 STRAITS VIEW MARINA ONE, SINGAPORE",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"shipper": "PT CITRA BORNEO UTAMA TBK"}',
        "document_text": "SHIPPER: PT CITRA BORNEO UTAMA TBK\nJALAN PELABUHAN ASDP, KALIMANTAN INDONESIA",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "HS code last-digit difference (expect FAIL)",
        "condition_text": "H.S. Code No. 9018.9050 must appear on the Bill of Lading.",
        "clause_ref": "47A-2",
        "lc_field_value": "9018.9050",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"hs_codes": ["9018909000"]}',
        "document_text": "HS CODE: 9018909000",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "NTN present but GST missing (expect FAIL)",
        "condition_text": "GST No. 03-00-3075811-17 must appear on the Bill of Lading.",
        "clause_ref": "46A-2",
        "lc_field_value": "03-00-3075811-17",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"ntn_number": "3075811-4"}',
        "document_text": "NTN NO. 3075811-4\nShipper: OLAM GLOBAL AGRI PTE LTD",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "CFR invoice without separate freight line (expect FAIL)",
        "condition_text": "Freight value should be mentioned on Commercial Invoice separately.",
        "clause_ref": "47A-8",
        "lc_field_value": "Freight separately",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"amount": "USD 97,216.00", "incoterms": "CFR KARACHI"}',
        "document_text": "TOTAL CFR KARACHI: USD 97,216.00\nInvoice Number: XPK-TRZ26030703",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Legitimate name prefix (LC truncated) (expect PASS)",
        "condition_text": "Shipment Advice must be addressed to the Applicant.",
        "clause_ref": "46A-3",
        "lc_field_value": "SINDH INSTITUTE OF UROLOGY AND",
        "lc_parties": "Applicant: SINDH INSTITUTE OF UROLOGY AND TRANSPLANTATION (SIUT), KARACHI, PAKISTAN",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": "",
        "document_text": "TO: SINDH INSTITUTE OF UROLOGY AND TRANSPLANTATION (SIUT), KARACHI, PAKISTAN\nSubject: Shipment Advice for L/C 0401ILC083248",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "BL notify includes issuing bank (expect PASS)",
        "condition_text": "Bill of Lading must be marked notify Bank Al Habib Ltd.",
        "clause_ref": "46A-2",
        "lc_field_value": "BANK AL HABIB LTD.",
        "lc_parties": "Issuing Bank: BANK AL HABIB LTD., PAKISTAN",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"notify_party": "TRANSSSION TECNO ELECTRONICS AND BANK AL HABIB LTD., KARACHI, PAKISTAN"}',
        "document_text": "NOTIFY PARTY: TRANSSSION TECNO ELECTRONICS (PVT) LTD. AND BANK AL HABIB LTD., KARACHI, PAKISTAN",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "BL notify does NOT include issuing bank (expect FAIL)",
        "condition_text": "Bill of Lading must be marked notify Bank Al Habib Ltd.",
        "clause_ref": "46A-2",
        "lc_field_value": "BANK AL HABIB LTD.",
        "lc_parties": "Issuing Bank: BANK AL HABIB LTD.",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"notify_party": "TRANSSSION TECNO ELECTRONICS (PVT) LTD."}',
        "document_text": "NOTIFY PARTY: TRANSSSION TECNO ELECTRONICS (PVT) LTD.",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "BL marked FREIGHT PREPAID (expect PASS)",
        "condition_text": "Bill of Lading must be marked 'Freight Prepaid'.",
        "clause_ref": "46A-2",
        "lc_field_value": "Freight Prepaid",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"freight_terms": "FREIGHT PREPAID"}',
        "document_text": "FREIGHT TERMS: FREIGHT PREPAID\nShipper has paid all freight.",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "BL with Freight COLLECT when LC wants PREPAID (expect FAIL)",
        "condition_text": "Bill of Lading must be marked 'Freight Prepaid'.",
        "clause_ref": "46A-2",
        "lc_field_value": "Freight Prepaid",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"freight_terms": "FREIGHT COLLECT"}',
        "document_text": "FREIGHT TERMS: FREIGHT COLLECT",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "HS code exact match with trailing zeros (expect PASS)",
        "condition_text": "H.S. Code No. 9018.9050 must appear on the Commercial Invoice.",
        "clause_ref": "47A-2",
        "lc_field_value": "9018.9050",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"hs_codes": ["9018905000"]}',
        "document_text": "HS CODE: 9018905000",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Invoice origin single country when multi required (expect FAIL)",
        "condition_text": "Commercial Invoice must certify Malaysia and Indonesia origin.",
        "clause_ref": "46A-1",
        "lc_field_value": "Malaysia and Indonesia origin",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"key_clauses": ["WE CERTIFY THAT MERCHANDISE ARE OF INDONESIA ORIGIN"]}',
        "document_text": "WE CERTIFY THAT MERCHANDISE ARE OF INDONESIA ORIGIN\nHS CODE 1511.9030",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Invoice covers both required origins (expect PASS)",
        "condition_text": "Commercial Invoice must certify Malaysia and Indonesia origin.",
        "clause_ref": "46A-1",
        "lc_field_value": "Malaysia and Indonesia origin",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"key_clauses": ["MERCHANDISE ARE OF MALAYSIA AND INDONESIA ORIGIN"]}',
        "document_text": "WE CERTIFY THAT MERCHANDISE ARE OF MALAYSIA AND INDONESIA ORIGIN",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Blank-back BL forbidden and BL IS blank back (expect FAIL)",
        "condition_text": "Bill of Lading must not be blank back.",
        "clause_ref": "47A-1",
        "lc_field_value": "NOT BLANK BACK",
        "lc_parties": "",
        "f47a_context": "STALE, CLAUSED, BLANK BACK, SHORT FORM AND/OR CHARTER PARTY BILL OF LADING NOT ACCEPTABLE.",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"has_terms_overleaf": false, "is_blank_back": true, "is_short_form": false, "form_type": "blank_back"}}',
        "document_text": "(no T&C page attached; front only)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Short-form BL forbidden but BL has T&C overleaf (expect PASS)",
        "condition_text": "Bill of Lading must not be short form.",
        "clause_ref": "47A-1",
        "lc_field_value": "NOT SHORT FORM",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"has_terms_overleaf": true, "is_blank_back": false, "is_short_form": false, "form_type": "long_form_printed_overleaf"}}',
        "document_text": "(BL with carriage T&Cs on separate overleaf page)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Consignee explicitly 'TO ORDER OF BANK' (expect PASS)",
        "condition_text": "Bill of Lading must be made out to the order of Bank Al Habib Ltd., Pakistan.",
        "clause_ref": "46A-2",
        "lc_field_value": "BANK AL HABIB LTD., PAKISTAN",
        "lc_parties": "Issuing Bank: BANK AL HABIB LTD., PAKISTAN",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"consignee": "TO THE ORDER OF BANK AL HABIB LTD., KARACHI, PAKISTAN"}',
        "document_text": "CONSIGNEE: TO THE ORDER OF BANK AL HABIB LTD., KARACHI, PAKISTAN",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Date reference mismatch (policy number) (expect FAIL)",
        "condition_text": "Commercial Invoice must reference Open Policy No. 2023008MIPD000453.",
        "clause_ref": "46A-3",
        "lc_field_value": "2023008MIPD000453",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"references_found": [{"role": "invoice_reference", "value": "XPK-TR26030303"}]}',
        "document_text": "INVOICE NO. XPK-TR26030303\nDate: 03-03-2026\n(no open policy reference anywhere)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Policy reference present with OCR O↔0 (expect PASS)",
        "condition_text": "Commercial Invoice must reference Open Policy No. 2023008MIPD000453.",
        "clause_ref": "46A-3",
        "lc_field_value": "2023008MIPD000453",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"references_found": [{"role": "open_policy_reference", "value": "2023008MIPDO00453"}]}',
        "document_text": "OPEN POLICY NO. 2023008MIPDO00453 (OCR misread O for 0)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Applicant address variation (expect PASS)",
        "condition_text": "Bill of Lading must be marked notify the Applicant.",
        "clause_ref": "46A-2",
        "lc_field_value": "TRANSSSION TECNO ELECTRONICS (PRIVATE) LIMITED. PLOT NO. 259/E, BLOCK-6, P.E.C.H.S OFF SHAHRAH-E-FAISAL KARACHI, PAKISTAN",
        "lc_parties": "Applicant: TRANSSSION TECNO ELECTRONICS (PRIVATE) LIMITED. PLOT NO. 259/E, BLOCK-6",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"notify_party": "TRANS SION TECNO ELECTRONICS (PRIVATE) LIMITED, PLOT NO.259/E, BLOCK-6, SHAHRAH-E-FAISAL KARACHI, PAKISTAN"}',
        "document_text": "NOTIFY PARTY: TRANS SION TECNO ELECTRONICS (PRIVATE) LIMITED, PLOT NO.259/E, BLOCK-6, SHAHRAH-E-FAISAL KARACHI, PAKISTAN",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ────────── Quantity / Amount ──────────
    {
        "name": "Invoice qty within +/- 2% tolerance (expect PASS)",
        "condition_text": "Quantity must be 250.00 M.Tons (+/- 2 PCT) on the Commercial Invoice.",
        "clause_ref": "45A-1",
        "lc_field_value": "250.00 M.Tons +/- 2 PCT",
        "lc_parties": "",
        "f47a_context": "PLUS MINUS 2 PCT TOLERANCE IS ALLOWED IN QUANTITY AND AMOUNT",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"quantities_found": [{"role": "quantity_shipped", "value": "248.500", "unit": "M.TONS"}]}',
        "document_text": "TOTAL QUANTITY: 248.500 M.TONS",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Invoice qty outside +/- 2% tolerance (expect FAIL)",
        "condition_text": "Quantity must be 250.00 M.Tons (+/- 2 PCT) on the Commercial Invoice.",
        "clause_ref": "45A-1",
        "lc_field_value": "250.00 M.Tons +/- 2 PCT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"quantities_found": [{"role": "quantity_shipped", "value": "260.000", "unit": "M.TONS"}]}',
        "document_text": "TOTAL QUANTITY: 260.000 M.TONS",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Invoice unit price matches LC (expect PASS)",
        "condition_text": "Unit price must be USD 1020.00 per M.Ton on the Commercial Invoice.",
        "clause_ref": "45A-1",
        "lc_field_value": "USD 1020.00 per M.Ton",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"amount": "USD 255000.00", "unit_price": "USD 1020.00/M.TON"}',
        "document_text": "Unit Price: USD 1020.00 per M.Ton\nQty: 250 M.Tons\nTotal: USD 255,000.00",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Invoice amount exceeds LC credit (expect FAIL)",
        "condition_text": "Commercial Invoice amount must not exceed the credit amount.",
        "clause_ref": "47A-9",
        "lc_field_value": "USD 255,000.00",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"amount": "USD 260100.00"}',
        "document_text": "Total Amount: USD 260,100.00",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ────────── Date checks ──────────
    {
        "name": "Document dated BEFORE LC issue (expect FAIL)",
        "condition_text": "Document must be dated on/after LC issue date (2025-12-31).",
        "clause_ref": "F31C",
        "lc_field_value": "2025-12-31",
        "lc_parties": "",
        "f47a_context": "DOCUMENTS DATED PRIOR TO DATE OF ISSUANCE OF THIS LC NOT ACCEPTABLE.",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"invoice_date": "2025-12-15"}',
        "document_text": "Invoice Date: 15-Dec-2025\nInvoice No. XPK-2025",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Document dated AFTER LC issue (expect PASS)",
        "condition_text": "Document must be dated on/after LC issue date (2025-12-31).",
        "clause_ref": "F31C",
        "lc_field_value": "2025-12-31",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"invoice_date": "2026-01-15"}',
        "document_text": "Invoice Date: 15-Jan-2026",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Shipment after latest shipment date (expect FAIL)",
        "condition_text": "Shipment must be on/before 2026-02-28.",
        "clause_ref": "F44C",
        "lc_field_value": "2026-02-28",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"onboard_date": "2026-03-11"}',
        "document_text": "SHIPPED ON BOARD: 11-MAR-2026",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "BL on board on or before latest shipment (expect PASS)",
        "condition_text": "Shipment must be on/before 2026-02-28.",
        "clause_ref": "F44C",
        "lc_field_value": "2026-02-28",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"onboard_date": "2026-02-20"}',
        "document_text": "SHIPPED ON BOARD: 20-FEB-2026",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Shipment advice within 4 working days (expect PASS)",
        "condition_text": "Shipment Advice must be dated within 4 working days after shipment.",
        "clause_ref": "46A-4",
        "lc_field_value": "4 working days",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": '{"shipment_date": "2026-01-30", "advice_sent_date": "2026-02-02"}',
        "document_text": "Shipment date: 30 Jan 2026\nAdvice sent: 02 Feb 2026 (3 working days later)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Shipment advice late (expect FAIL)",
        "condition_text": "Shipment Advice must be dated within 4 working days after shipment.",
        "clause_ref": "46A-4",
        "lc_field_value": "4 working days",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": '{"shipment_date": "2026-01-30", "advice_sent_date": "2026-02-10"}',
        "document_text": "Shipment date: 30 Jan 2026\nAdvice sent: 10 Feb 2026 (8 working days later)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ────────── Port checks ──────────
    {
        "name": "Port of Loading matches LC (expect PASS)",
        "condition_text": "Port of Loading must match ANY MALAYSIA PORT.",
        "clause_ref": "F44E",
        "lc_field_value": "ANY MALAYSIA PORT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"port_of_loading": "PENANG, MALAYSIA"}',
        "document_text": "PORT OF LOADING: PENANG, MALAYSIA",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Port of Loading wrong country (expect FAIL)",
        "condition_text": "Port of Loading must match ANY MALAYSIA PORT.",
        "clause_ref": "F44E",
        "lc_field_value": "ANY MALAYSIA PORT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"port_of_loading": "CHITTAGONG, BANGLADESH"}',
        "document_text": "PORT OF LOADING: CHITTAGONG, BANGLADESH",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ────────── Certificates / Signed / Copies ──────────
    {
        "name": "Commercial Invoice signed (expect PASS)",
        "condition_text": "A signed Commercial Invoice must be present in the submission.",
        "clause_ref": "46A-1",
        "lc_field_value": "signed invoice",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"signed_by": "OLAM GLOBAL AGRI PTE LTD — authorized signatory (handwritten signature)"}',
        "document_text": "For OLAM GLOBAL AGRI PTE LTD\n(signature)\nAuthorized Signatory",
        "visual_metadata": "Signatures: [handwritten signature of authorized signatory]",
        "expected_verdict": "PASS",
    },
    {
        "name": "Commercial Invoice unsigned (expect FAIL)",
        "condition_text": "A signed Commercial Invoice must be present in the submission.",
        "clause_ref": "46A-1",
        "lc_field_value": "signed invoice",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"signed_by": ""}',
        "document_text": "(no signature block visible on invoice)",
        "visual_metadata": "Signatures: []",
        "expected_verdict": "FAIL",
    },
    # ────────── BL subtype / 47A-10 / 47A-3 ──────────
    {
        "name": "BL signed as agent for master (not forwarder) (expect PASS)",
        "condition_text": "Bill of Lading must not be a Freight Forwarder's Bill of Lading.",
        "clause_ref": "47A-3",
        "lc_field_value": "not a freight forwarder's BL",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"signing_type": "agent_for_master", "forwarder_name": ""}}',
        "document_text": "Signed by HUAN MING INTERNATIONAL SHIPPING AGENCY CO., LTD AS AGENT FOR CARRIER YANG MING (SINGAPORE)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "BL issued by freight forwarder (expect FAIL)",
        "condition_text": "Bill of Lading must not be a Freight Forwarder's Bill of Lading.",
        "clause_ref": "47A-3",
        "lc_field_value": "not a freight forwarder's BL",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"signing_type": "forwarder_signed", "forwarder_name": "ACME FREIGHT FORWARDERS INC."}}',
        "document_text": "HOUSE BILL OF LADING issued by ACME FREIGHT FORWARDERS INC. as forwarder",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "BL shows FIATA (freight forwarder flag) (expect FAIL)",
        "condition_text": "Bill of Lading must not show words like 'FIATA'.",
        "clause_ref": "47A-10",
        "lc_field_value": "no FIATA",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": "",
        "document_text": "FIATA MULTIMODAL TRANSPORT BILL OF LADING\nIssued in accordance with FIATA rules.",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "BL without FIATA or forwarder marks (expect PASS)",
        "condition_text": "Bill of Lading must not show words like 'FIATA'.",
        "clause_ref": "47A-10",
        "lc_field_value": "no FIATA",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": "",
        "document_text": "OCEAN BILL OF LADING\nIssued by YANG MING (SINGAPORE) PTE LTD",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ────────── Draft / BoE ──────────
    {
        "name": "Draft states AT SIGHT per LC (expect PASS)",
        "condition_text": "Draft tenor must match LC: AT SIGHT.",
        "clause_ref": "F42C",
        "lc_field_value": "AT SIGHT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Draft Bill of Exchange",
        "structured_facts": '{"tenor": "AT SIGHT"}',
        "document_text": "AT SIGHT of this First of Exchange pay to the order of OLAM GLOBAL AGRI",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Draft states 60 days sight but LC is AT SIGHT (expect FAIL)",
        "condition_text": "Draft tenor must match LC: AT SIGHT.",
        "clause_ref": "F42C",
        "lc_field_value": "AT SIGHT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Draft Bill of Exchange",
        "structured_facts": '{"tenor": "60 DAYS AFTER SIGHT"}',
        "document_text": "At 60 DAYS AFTER SIGHT of this first of exchange pay to the order of...",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Draft carries LC number (expect PASS)",
        "condition_text": "Documentary Credit number must appear on the Draft.",
        "clause_ref": "47A-2",
        "lc_field_value": "0005LC90854/2025",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Draft Bill of Exchange",
        "structured_facts": '{"references_found": [{"role": "lc_reference", "value": "0005LC90854/2025"}]}',
        "document_text": "DRAWN UNDER L/C NO. 0005LC90854/2025 DATED 31-12-2025",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ────────── Insurance / Institute Classification Clause ──────────
    {
        "name": "Vessel covered under Institute Classification Clause (expect PASS)",
        "condition_text": "Certificate must state that the carrying vessel is covered under Institute Classification Clause.",
        "clause_ref": "46A-3",
        "lc_field_value": "Institute Classification Clause",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Shipping Company Certificate",
        "structured_facts": '{"key_clauses": ["WE CERTIFY THAT THE VESSEL MV NCC SAMA IS COVERED UNDER INSTITUTE CLASSIFICATION CLAUSE"]}',
        "document_text": "WE CERTIFY THAT THE VESSEL MV NCC SAMA IS COVERED UNDER INSTITUTE CLASSIFICATION CLAUSE 1-1-2001",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "No mention of Institute Classification Clause (expect FAIL)",
        "condition_text": "Certificate must state that the carrying vessel is covered under Institute Classification Clause.",
        "clause_ref": "46A-3",
        "lc_field_value": "Institute Classification Clause",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Shipping Company Certificate",
        "structured_facts": "",
        "document_text": "This is to certify that the vessel is seaworthy and meets international shipping standards.",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ────────── Survey / Weight / Quality / Phytosanitary ──────────
    {
        "name": "Survey Report issued by independent surveyor (expect PASS)",
        "condition_text": "The Survey Report must be issued by an internationally independent surveyor.",
        "clause_ref": "46A-7",
        "lc_field_value": "independent internationally recognized surveyor",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Survey Report",
        "structured_facts": '{"issuer": "ALFRED H KNIGHT — independent international surveyor"}',
        "document_text": "ALFRED H KNIGHT\nIndependent International Surveyor\nAHK REFERENCE AGRI/10218",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Weight Certificate final at load port (expect PASS)",
        "condition_text": "The Weight and Quality Certificate must be final at the load port.",
        "clause_ref": "46A-6",
        "lc_field_value": "final at load port",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Weight / Quality Certificate",
        "structured_facts": '{"key_clauses": ["Final weight and quality determined at load port."]}',
        "document_text": "We certify final weight and quality at load port of 249.500 M.Tons of RBD Palm Olein",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ────────── Beneficiary Certificate ──────────
    {
        "name": "Benef Cert says docs sent to applicant (expect PASS)",
        "condition_text": "A complete set of non-negotiable documents has been sent to the applicant.",
        "clause_ref": "46A-8",
        "lc_field_value": "non-negotiable documents sent to applicant",
        "lc_parties": "Applicant: SIALKOT OIL REFINERY",
        "f47a_context": "",
        "document_type": "Beneficiary Certificate",
        "structured_facts": "",
        "document_text": "WE HEREBY CERTIFY THAT ONE SET OF NON-NEGOTIABLE DOCUMENTS HAS BEEN SENT TO THE APPLICANT, SIALKOT OIL REFINERY, BY DHL COURIER.",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ────────── Transshipment ──────────
    {
        "name": "Transshipment NOT ALLOWED but BL shows transshipment (expect FAIL)",
        "condition_text": "Transshipment: NOT ALLOWED.",
        "clause_ref": "F43T",
        "lc_field_value": "NOT ALLOWED",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"key_clauses": ["TRANSSHIPMENT AT SINGAPORE TO MV FEEDER VESSEL"]}',
        "document_text": "Place of Delivery: KARACHI via transshipment at SINGAPORE onto MV FEEDER VESSEL",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Transshipment NOT ALLOWED and BL has no transshipment (expect PASS)",
        "condition_text": "Transshipment: NOT ALLOWED.",
        "clause_ref": "F43T",
        "lc_field_value": "NOT ALLOWED",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"vessel_name": "MT NCC SAMA", "voyage_number": "202603"}',
        "document_text": "Onboard the vessel MT NCC SAMA voyage 202603 direct from PORT DICKSON to KARACHI",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ────────── Multi-country origin ──────────
    {
        "name": "Invoice covers multiple countries as required (expect PASS)",
        "condition_text": "Invoices must mention multiple countries of origin covering the shipment.",
        "clause_ref": "46A-12",
        "lc_field_value": "multiple countries of origin",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": "",
        "document_text": "COUNTRY OF ORIGIN: MALAYSIA AND INDONESIA",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Invoice single origin when multi required (expect FAIL)",
        "condition_text": "Invoices must mention multiple countries of origin covering the shipment.",
        "clause_ref": "46A-12",
        "lc_field_value": "multiple countries of origin",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": "",
        "document_text": "COUNTRY OF ORIGIN: INDONESIA",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ────────── English language ──────────
    {
        "name": "Document in English (expect PASS)",
        "condition_text": "All documents must be made out in English language.",
        "clause_ref": "47A-5",
        "lc_field_value": "English language",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": "",
        "document_text": "COMMERCIAL INVOICE\nSeller: OLAM\nBuyer: SIALKOT\nDescription: Palm Olein in bulk, CFR KARACHI",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Document in Chinese (expect FAIL)",
        "condition_text": "All documents must be made out in English language.",
        "clause_ref": "47A-5",
        "lc_field_value": "English language",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": "",
        "document_text": "商业发票\n卖方: 公司甲\n买方: 公司乙\n(entirely in Chinese characters)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ══════════════ SHIPPING DOC DEEP-DIVE ══════════════════════════
    # ── Bill of Lading ──
    {
        "name": "Clean BL (no clausing notes) (expect PASS)",
        "condition_text": "Bill of Lading must be clean (no clausing notations on goods).",
        "clause_ref": "46A-2",
        "lc_field_value": "clean on board",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"cleanness": "clean", "is_claused_bl": false, "clausing_notes": ""}}',
        "document_text": "CLEAN ON BOARD — no damage or defect noted on goods.",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Claused BL with damage notation (expect FAIL)",
        "condition_text": "Bill of Lading must not be claused.",
        "clause_ref": "47A-1",
        "lc_field_value": "not claused",
        "lc_parties": "",
        "f47a_context": "CLAUSED BILL OF LADING NOT ACCEPTABLE.",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"cleanness": "claused", "is_claused_bl": true, "clausing_notes": "2 CARTONS DAMAGED IN HANDLING"}}',
        "document_text": "REMARKS: 2 CARTONS DAMAGED IN HANDLING",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "BL has 'Shipped on Board' notation (expect PASS)",
        "condition_text": "Bill of Lading must show 'Shipped on Board' notation.",
        "clause_ref": "46A-2",
        "lc_field_value": "Shipped on Board",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"shipped_on_board_status": "shipped_on_board", "onboard_date": "2026-03-11"}',
        "document_text": "SHIPPED ON BOARD 11-MAR-2026",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Received-for-Shipment BL (no on-board notation) (expect FAIL)",
        "condition_text": "Bill of Lading must show 'Shipped on Board' notation.",
        "clause_ref": "46A-2",
        "lc_field_value": "Shipped on Board",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"shipped_on_board_status": "received_for_shipment"}',
        "document_text": "RECEIVED FOR SHIPMENT by carrier at CY — no on-board stamp.",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Full set 3/3 originals present (expect PASS)",
        "condition_text": "Full set of 3 originals of Bill of Lading must be presented.",
        "clause_ref": "46A-2",
        "lc_field_value": "full set 3 originals",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"number_of_originals": "3"}',
        "document_text": "Number of Original Bs/L: 3 (THREE)\nORIGINAL / ORIGINAL / ORIGINAL",
        "visual_metadata": "Copy Status: original",
        "expected_verdict": "PASS",
    },
    {
        "name": "Only non-negotiable copies presented (expect FAIL)",
        "condition_text": "Full set of original Bill of Lading must be presented.",
        "clause_ref": "46A-2",
        "lc_field_value": "full set originals",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"copy_status": "non_negotiable", "copy_label": "NON-NEGOTIABLE"}',
        "document_text": "NON-NEGOTIABLE COPY — NOT ORIGINAL",
        "visual_metadata": "Copy Status: non_negotiable",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Charter Party BL allowed per F47A (expect PASS)",
        "condition_text": "Bill of Lading must not be a Charter Party BL.",
        "clause_ref": "47A-1",
        "lc_field_value": "not charter party",
        "lc_parties": "",
        "f47a_context": "CHARTER PARTY, SHORT FORM, BLANK BACK AND TANKER BL ARE ACCEPTABLE.",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"contract_type": "charter_party"}}',
        "document_text": "CHARTER PARTY BILL OF LADING per CP dated 15-Jan-2026",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Container numbers match across BL & Packing List (expect PASS)",
        "condition_text": "Container numbers on Bill of Lading must match Packing List.",
        "clause_ref": "46A-2",
        "lc_field_value": "container numbers",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"container_numbers": ["YMLU8681239", "YMLU8681245"]}',
        "document_text": "CONTAINER NOS: YMLU8681239 / YMLU8681245\n(packing list also lists YMLU8681239 and YMLU8681245)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Commercial Invoice ──
    {
        "name": "Invoice in octuplicate (8 copies) (expect PASS)",
        "condition_text": "Commercial Invoice must be in octuplicate (8 copies).",
        "clause_ref": "46A-1",
        "lc_field_value": "octuplicate / 8 copies",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"number_of_originals": "8"}',
        "document_text": "(8 separate copies of the same Commercial Invoice present in submission)",
        "visual_metadata": "Copy Status: 8 copies",
        "expected_verdict": "PASS",
    },
    {
        "name": "Invoice made out in name of applicant (expect PASS)",
        "condition_text": "Commercial Invoice must be made out in the name of the Applicant.",
        "clause_ref": "46A-1",
        "lc_field_value": "made out to Applicant",
        "lc_parties": "Applicant: SIALKOT OIL REFINERY (PVT) LTD., PAKISTAN",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": "",
        "document_text": "To: SIALKOT OIL REFINERY (PVT) LTD., PAKISTAN\nInvoice No. OGA-2026-001",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Invoice billed to wrong party (expect FAIL)",
        "condition_text": "Commercial Invoice must be made out in the name of the Applicant.",
        "clause_ref": "46A-1",
        "lc_field_value": "made out to Applicant",
        "lc_parties": "Applicant: SIALKOT OIL REFINERY (PVT) LTD., PAKISTAN",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": "",
        "document_text": "To: LAHORE TEXTILE MILLS LTD., LAHORE\nInvoice No. OGA-2026-001",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Packing List ──
    {
        "name": "Packing List total packages matches BL (expect PASS)",
        "condition_text": "Packing List number of packages must match the BL's package count.",
        "clause_ref": "46A-2",
        "lc_field_value": "packages match BL",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Packing List",
        "structured_facts": '{"number_of_packages": "17 PACKAGES"}',
        "document_text": "TOTAL PACKED IN 17 PACKAGES (matches BL's 17-package count)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Packing List shipping marks match BL (expect PASS)",
        "condition_text": "Shipping marks on Packing List must match Bill of Lading.",
        "clause_ref": "46A-2",
        "lc_field_value": "shipping marks match",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Packing List",
        "structured_facts": '{"marks_and_numbers": "INFINIX MOBILITY / LC 5001LC60733/2026 / KARACHI"}',
        "document_text": "SHIPPING MARKS: INFINIX MOBILITY / LC 5001LC60733/2026 / KARACHI\n(BL shows same marks)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Insurance Policy ──
    {
        "name": "Insurance coverage 110% of CIF (expect PASS)",
        "condition_text": "Insurance must cover 110% of CIF value.",
        "clause_ref": "46A-3",
        "lc_field_value": "110% CIF value",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Insurance Policy",
        "structured_facts": '{"amount": "USD 280,500.00", "key_clauses": ["Insured value 110% of CIF USD 255,000"]}',
        "document_text": "Sum insured: USD 280,500.00 (110% of CIF USD 255,000.00)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Insurance only 100% of CIF (expect FAIL)",
        "condition_text": "Insurance must cover 110% of CIF value.",
        "clause_ref": "46A-3",
        "lc_field_value": "110% CIF value",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Insurance Policy",
        "structured_facts": '{"amount": "USD 255,000.00"}',
        "document_text": "Sum insured: USD 255,000.00 (= 100% of CIF)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Insurance covers Institute Cargo Clauses A (expect PASS)",
        "condition_text": "Insurance must cover risks per Institute Cargo Clauses (A).",
        "clause_ref": "46A-3",
        "lc_field_value": "Institute Cargo Clauses (A)",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Insurance Policy",
        "structured_facts": "",
        "document_text": "INSTITUTE CARGO CLAUSES (A) 1/1/2009\nINSTITUTE WAR CLAUSES\nINSTITUTE STRIKES CLAUSES",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Certificate of Origin ──
    {
        "name": "Certificate of Origin shows correct country (expect PASS)",
        "condition_text": "Certificate of Origin must certify country of origin: Malaysia.",
        "clause_ref": "46A-12",
        "lc_field_value": "Malaysia",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Certificate of Origin",
        "structured_facts": '{"country_of_origin": "MALAYSIA"}',
        "document_text": "COUNTRY OF ORIGIN: MALAYSIA\nIssued by: Malaysian Chamber of Commerce",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Certificate of Origin wrong country (expect FAIL)",
        "condition_text": "Certificate of Origin must certify country of origin: Malaysia.",
        "clause_ref": "46A-12",
        "lc_field_value": "Malaysia",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Certificate of Origin",
        "structured_facts": '{"country_of_origin": "INDONESIA"}',
        "document_text": "COUNTRY OF ORIGIN: INDONESIA",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Draft / Drawee ──
    {
        "name": "Draft drawn on correct issuing bank (expect PASS)",
        "condition_text": "Draft must be drawn on Bank Al Habib Limited, Pakistan.",
        "clause_ref": "F42D",
        "lc_field_value": "BANK AL HABIB LIMITED, PAKISTAN",
        "lc_parties": "Drawee: BANK AL HABIB LIMITED",
        "f47a_context": "",
        "document_type": "Draft Bill of Exchange",
        "structured_facts": '{"drawee": "BANK AL HABIB LIMITED, KARACHI"}',
        "document_text": "DRAWN ON BANK AL HABIB LIMITED KARACHI\nUNDER L/C NO. 0005LC90854/2025",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Draft drawn on wrong bank (expect FAIL)",
        "condition_text": "Draft must be drawn on Bank Al Habib Limited, Pakistan.",
        "clause_ref": "F42D",
        "lc_field_value": "BANK AL HABIB LIMITED, PAKISTAN",
        "lc_parties": "Drawee: BANK AL HABIB LIMITED",
        "f47a_context": "",
        "document_type": "Draft Bill of Exchange",
        "structured_facts": '{"drawee": "HABIB BANK LIMITED"}',
        "document_text": "DRAWN ON HABIB BANK LIMITED (HBL)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Drafts issued by beneficiary (not third party) ──
    {
        "name": "Draft issued by beneficiary (expect PASS)",
        "condition_text": "Draft must be issued by the beneficiary, not a third party.",
        "clause_ref": "47A-11",
        "lc_field_value": "issued by beneficiary",
        "lc_parties": "Beneficiary: OLAM GLOBAL AGRI PTE LTD",
        "f47a_context": "",
        "document_type": "Draft Bill of Exchange",
        "structured_facts": '{"drawer": "OLAM GLOBAL AGRI PTE LTD"}',
        "document_text": "For and on behalf of OLAM GLOBAL AGRI PTE LTD (Drawer)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Doc Remittance / Receiving Date ──
    {
        "name": "DR receiving date within presentation period (expect PASS)",
        "condition_text": "Documents must be presented within 21 days of shipment.",
        "clause_ref": "F48",
        "lc_field_value": "21 days",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Documentary Remittance",
        "structured_facts": '{"shipment_date": "2026-01-30", "receiving_date": "2026-02-15"}',
        "document_text": "Shipment date: 30-Jan-2026\nDocuments received at bank: 15-Feb-2026 (16 days later)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "DR receiving date BEYOND presentation period (expect FAIL)",
        "condition_text": "Documents must be presented within 21 days of shipment.",
        "clause_ref": "F48",
        "lc_field_value": "21 days",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Documentary Remittance",
        "structured_facts": '{"shipment_date": "2026-01-30", "receiving_date": "2026-03-15"}',
        "document_text": "Shipment date: 30-Jan-2026\nDocuments received at bank: 15-Mar-2026 (44 days later)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Stale BL (30 days) ──
    {
        "name": "Stale BL (>30 days between onboard and receiving) (expect FAIL)",
        "condition_text": "Bill of Lading must not be stale (onboard date to presentation ≤30 days).",
        "clause_ref": "47A-1",
        "lc_field_value": "not stale",
        "lc_parties": "",
        "f47a_context": "STALE BL NOT ACCEPTABLE.",
        "document_type": "Bill of Lading",
        "structured_facts": '{"onboard_date": "2025-09-01", "presentation_date": "2025-10-10"}',
        "document_text": "SHIPPED ON BOARD 01-SEP-2025\nBank received: 10-OCT-2025 (39 days later — stale)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Non-stale BL (<30 days) (expect PASS)",
        "condition_text": "Bill of Lading must not be stale (onboard date to presentation ≤30 days).",
        "clause_ref": "47A-1",
        "lc_field_value": "not stale",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"onboard_date": "2026-01-30", "presentation_date": "2026-02-15"}',
        "document_text": "SHIPPED ON BOARD 30-JAN-2026\nBank received: 15-FEB-2026 (16 days — within 30-day window)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Multi-doc fan-out: LC number on ALL docs ──
    {
        "name": "LC number missing on Packing List (expect FAIL)",
        "condition_text": "L/C NUMBER should appear on ALL documents and Bill of Lading.",
        "clause_ref": "47A-2",
        "lc_field_value": "LC NO. 5001LC60733/2026",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Packing List",
        "structured_facts": '{"references_found": []}',
        "document_text": "PACKING LIST\nShipper: INFINIX MOBILITY\n(no LC number anywhere on the document)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "LC number present on Commercial Invoice (expect PASS)",
        "condition_text": "L/C NUMBER should appear on ALL documents and Bill of Lading.",
        "clause_ref": "47A-2",
        "lc_field_value": "LC NO. 5001LC60733/2026",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"lc_reference": "5001LC60733/2026"}',
        "document_text": "DOCUMENTARY CREDIT NO.: 5001LC60733/2026\nDate of Issue: 2026/3/4",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Halal Certificate ──
    {
        "name": "Halal Cert from accredited body (expect PASS)",
        "condition_text": "Halal Certificate must be issued by a Halal Certification Body accredited with an AB that is an IHAF member.",
        "clause_ref": "46A-11",
        "lc_field_value": "IHAF-accredited halal cert body",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Halal Certificate",
        "structured_facts": "",
        "document_text": "Issued by JAKIM Malaysia, accredited with JAS-ANZ, an IHAF member accreditation body.",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ══════════════ EDGE CASES / MISSING DOCS / TOLERANCE ══════════
    # ── Tolerance boundaries ──
    {
        "name": "Quantity EXACTLY at +2% tolerance boundary (expect PASS)",
        "condition_text": "Quantity must be 250.00 M.Tons (+/- 2 PCT) on the Commercial Invoice.",
        "clause_ref": "45A-1",
        "lc_field_value": "250.00 M.Tons +/- 2 PCT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"quantities_found": [{"role": "quantity_shipped", "value": "255.000", "unit": "M.TONS"}]}',
        "document_text": "TOTAL QUANTITY: 255.000 M.TONS (exactly +2% of 250)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Quantity 1 unit OVER +2% tolerance (expect FAIL)",
        "condition_text": "Quantity must be 250.00 M.Tons (+/- 2 PCT) on the Commercial Invoice.",
        "clause_ref": "45A-1",
        "lc_field_value": "250.00 M.Tons +/- 2 PCT",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"quantities_found": [{"role": "quantity_shipped", "value": "256.000", "unit": "M.TONS"}]}',
        "document_text": "TOTAL QUANTITY: 256.000 M.TONS (exceeds 2% tolerance of 255)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── F47A overrides (things normally FAIL become PASS) ──
    {
        "name": "Late shipment normally FAIL but F47A ALLOWS (expect PASS)",
        "condition_text": "Shipment must be on/before 2026-02-28.",
        "clause_ref": "F44C",
        "lc_field_value": "2026-02-28",
        "lc_parties": "",
        "f47a_context": "LATE SHIPMENT ALLOWED WITHOUT DEDUCTION.",
        "document_type": "Bill of Lading",
        "structured_facts": '{"onboard_date": "2026-03-11"}',
        "document_text": "SHIPPED ON BOARD: 11-MAR-2026",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Third-party docs F47A ACCEPTABLE (expect PASS)",
        "condition_text": "Commercial Invoice must be issued by the beneficiary, not a third party.",
        "clause_ref": "47A-11",
        "lc_field_value": "beneficiary only, no third party",
        "lc_parties": "Beneficiary: OLAM GLOBAL AGRI PTE LTD",
        "f47a_context": "THIRD PARTY DOCUMENTS ACCEPTABLE.",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"issuer": "PT CITRA BORNEO UTAMA TBK (third party)"}',
        "document_text": "Issued by PT CITRA BORNEO UTAMA TBK on behalf of OLAM GLOBAL AGRI PTE LTD",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "Charter Party BL FAIL but F47A ACCEPTABLE (expect PASS)",
        "condition_text": "Bill of Lading must not be a Charter Party BL.",
        "clause_ref": "47A-1",
        "lc_field_value": "not charter party",
        "lc_parties": "",
        "f47a_context": "CHARTER PARTY BL ACCEPTABLE.",
        "document_type": "Bill of Lading",
        "structured_facts": '{"bl_subtype": {"contract_type": "charter_party"}}',
        "document_text": "CHARTER PARTY BILL OF LADING per CP dated 15-Jan-2026",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Missing document scenarios ──
    {
        "name": "Courier Receipt missing from submission (expect FAIL)",
        "condition_text": "Courier Receipt must exist proving Shipment Advice was dispatched.",
        "clause_ref": "46A-4",
        "lc_field_value": "Courier Receipt",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Courier Receipt",
        "structured_facts": "(no such document in submission)",
        "document_text": "(document not in submission)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Halal Certificate missing (expect FAIL)",
        "condition_text": "Halal Certificate must accompany the documents.",
        "clause_ref": "46A-11",
        "lc_field_value": "Halal Certificate",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Halal Certificate",
        "structured_facts": "(no such document in submission)",
        "document_text": "(document not in submission)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Ambiguous OCR / noisy text ──
    {
        "name": "OCR with 0/O confusion in LC reference (expect PASS)",
        "condition_text": "Commercial Invoice must reference L/C No. 0005LC90854/2025.",
        "clause_ref": "47A-2",
        "lc_field_value": "0005LC90854/2025",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"lc_reference": "OOO5LC9O854/2O25"}',
        "document_text": "LC NO.: OOO5LC9O854/2O25 (OCR confused 0→O in multiple positions)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    {
        "name": "OCR I/1 confusion in a digit sequence (expect PASS)",
        "condition_text": "Commercial Invoice must show NTN NO. 3075811-4.",
        "clause_ref": "47A-2",
        "lc_field_value": "3075811-4",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"ntn_number": "30758I1-4"}',
        "document_text": "NTN NO.: 30758I1-4 (OCR misread 1 as I)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Same-clause multiple conditions independence ──
    {
        "name": "Partial compliance: one sub-condition met, another missing (expect FAIL)",
        "condition_text": "Bill of Lading must show IMO number of the vessel.",
        "clause_ref": "46A-2",
        "lc_field_value": "IMO number",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"vessel_name": "MT NCC SAMA"}',
        "document_text": "Vessel: MT NCC SAMA (no IMO number shown anywhere)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "IMO number present on BL (expect PASS)",
        "condition_text": "Bill of Lading must show IMO number of the vessel.",
        "clause_ref": "46A-2",
        "lc_field_value": "IMO number",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Bill of Lading",
        "structured_facts": '{"vessel_name": "MT NCC SAMA", "vessel_imo": "9324001"}',
        "document_text": "Vessel: MT NCC SAMA (IMO 9324001)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Wrong doc type for the check ──
    {
        "name": "Applying notify-party check to an Invoice (not applicable) (expect REVIEW)",
        "condition_text": "Bill of Lading must be marked to notify the Applicant.",
        "clause_ref": "46A-2",
        "lc_field_value": "notify applicant",
        "lc_parties": "Applicant: SIALKOT OIL REFINERY",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"doc_type": "Commercial Invoice"}',
        "document_text": "Commercial Invoice\nSeller / Buyer / Amount — no notify party field on invoices.",
        "visual_metadata": "",
        "expected_verdict": "REVIEW",
    },
    # ── Insurance risks specific ──
    {
        "name": "Insurance missing War Risks clause (expect FAIL)",
        "condition_text": "Insurance must cover Institute War Clauses.",
        "clause_ref": "46A-3",
        "lc_field_value": "Institute War Clauses",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Insurance Policy",
        "structured_facts": "",
        "document_text": "Covers: Institute Cargo Clauses (A) 1/1/2009. No war clause listed.",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Boundary: name spelled with minor typo ──
    {
        "name": "Beneficiary name with one-letter typo (expect PASS)",
        "condition_text": "Commercial Invoice must be issued by the beneficiary OLAM GLOBAL AGRI PTE LTD.",
        "clause_ref": "47A-11",
        "lc_field_value": "OLAM GLOBAL AGRI PTE LTD",
        "lc_parties": "Beneficiary: OLAM GLOBAL AGRI PTE LTD",
        "f47a_context": "",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"issuer": "OLAM GLOBLE AGRI PTE LTD"}',
        "document_text": "Issued by OLAM GLOBLE AGRI PTE LTD (OCR typo: GLOBLE vs GLOBAL)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Different party (not a typo) ──
    {
        "name": "Applicant vs similar-sounding but different company (expect FAIL)",
        "condition_text": "Shipment Advice must be addressed to the Applicant.",
        "clause_ref": "46A-3",
        "lc_field_value": "SINDH INSTITUTE OF UROLOGY AND TRANSPLANTATION",
        "lc_parties": "Applicant: SINDH INSTITUTE OF UROLOGY AND TRANSPLANTATION, KARACHI",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": "",
        "document_text": "TO: M/S SINDH INSURANCE COMPANY, KARACHI (a different entity — insurance vs urology institute)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── BL date mismatch across docs ──
    {
        "name": "Shipment Advice quotes wrong BL date (expect FAIL)",
        "condition_text": "Shipment Advice must show the BL onboard date.",
        "clause_ref": "46A-4",
        "lc_field_value": "BL onboard date",
        "lc_parties": "",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": '{"onboard_date_claimed": "2026-02-15", "bl_actual_onboard": "2026-01-30"}',
        "document_text": "Shipment sailed on 15-Feb-2026 (but the actual BL onboard date is 30-Jan-2026 — mismatch)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    # ── Multiple recipients in Shipment Advice ──
    {
        "name": "Shipment Advice includes only ONE of two required recipients (expect FAIL)",
        "condition_text": "Shipment Advice must be addressed to Asia Insurance Company Ltd. AND to the Applicant.",
        "clause_ref": "46A-3",
        "lc_field_value": "Asia Insurance Company Ltd. and the Applicant",
        "lc_parties": "Applicant: M/S ALI ENTERPRISES",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": "",
        "document_text": "TO: ASIA INSURANCE COMPANY LIMITED, LAHORE, PAKISTAN\n(no Applicant recipient listed)",
        "visual_metadata": "",
        "expected_verdict": "FAIL",
    },
    {
        "name": "Shipment Advice has BOTH required recipients (expect PASS)",
        "condition_text": "Shipment Advice must be addressed to Asia Insurance Company Ltd. AND to the Applicant.",
        "clause_ref": "46A-3",
        "lc_field_value": "Asia Insurance Company Ltd. and the Applicant",
        "lc_parties": "Applicant: M/S ALI ENTERPRISES",
        "f47a_context": "",
        "document_type": "Shipment Advice",
        "structured_facts": "",
        "document_text": "TO: ASIA INSURANCE COMPANY LIMITED, LAHORE, PAKISTAN\nAND TO: M/S ALI ENTERPRISES (Applicant)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
    # ── Invoice value tolerance for partial shipment ──
    {
        "name": "Partial shipment allowed, invoice less than LC (expect PASS)",
        "condition_text": "Commercial Invoice amount must not exceed the credit amount.",
        "clause_ref": "47A-9",
        "lc_field_value": "USD 255,000.00",
        "lc_parties": "",
        "f47a_context": "PARTIAL SHIPMENT ALLOWED.",
        "document_type": "Commercial Invoice",
        "structured_facts": '{"amount": "USD 127500.00"}',
        "document_text": "Invoice amount: USD 127,500.00 (50% partial shipment)",
        "visual_metadata": "",
        "expected_verdict": "PASS",
    },
]


def run_case(c):
    prompt = CORE_VERIFICATION_PROMPT.format(
        condition_text=c["condition_text"],
        clause_ref=c["clause_ref"],
        lc_field_value=c["lc_field_value"],
        lc_parties=c["lc_parties"],
        f47a_context=c["f47a_context"],
        document_type=c["document_type"],
        structured_facts=c["structured_facts"],
        document_text=c["document_text"],
        visual_metadata=c["visual_metadata"],
        family_pack="",
    )
    body = {
        "model": QWEN_TEXT_LLM_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.0,
        "max_tokens": 800,
    }
    t0 = time.time()
    try:
        r = requests.post(QWEN_TEXT_LLM_URL, json=body, timeout=300)
        r.raise_for_status()
        resp = r.json()
        content = resp["choices"][0]["message"]["content"]
        dt = time.time() - t0
    except Exception as e:
        return f"REQUEST FAILED: {e}", None, 0.0

    # Parse verdict from response (it returns JSON with a verdict key)
    verdict = "?"
    try:
        import re
        m = re.search(r'"verdict"\s*:\s*"([A-Za-z_]+)"', content)
        if not m:
            m = re.search(r'"compliance"\s*:\s*"([A-Za-z_]+)"', content)
        if m:
            verdict = m.group(1).upper()
    except Exception:
        pass
    return verdict, content[:400], dt


def main():
    print(f"LLM: {QWEN_TEXT_LLM_URL}")
    print(f"Model: {QWEN_TEXT_LLM_MODEL}")
    print("=" * 60)
    results = []
    for c in CASES:
        verdict, snippet, dt = run_case(c)
        ok = verdict == c["expected_verdict"]
        mark = "OK " if ok else "XX "
        results.append(ok)
        print(f"\n{mark} {c['name']}")
        print(f"     expected={c['expected_verdict']}, got={verdict}, time={dt:.1f}s")
        if snippet:
            # show just the verdict + findings line
            print(f"     response[:200]: {snippet[:200]}")
    print("\n" + "=" * 60)
    ok_n = sum(1 for x in results if x)
    print(f"RESULT: {ok_n}/{len(results)} pass")


if __name__ == "__main__":
    main()
